#!/bin/sh

# locale
export LANG=zh_CN.UTF-8

# Default programs
export TERMINAL=foot
export MANPAGER='nvim +Man!'
export EDITOR="nvim"
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"

export ALSA_CARD=Genric

# XDG paths
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# Fixing Paths
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$XDG_DATA_HOME/history"
export GOPATH="$XDG_DATA_HOME/go"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
export CARGO_HOME="$HOME/.cargo"
export RUSTUP_HOME="$HOME/.rustup"

export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT="MToolkit wmname LG3D" # fix Java applications

# Paths
export PATH="$CARGO_HOME/bin:$PATH"
